name: Build

on:
  push:
    paths:
      - .github/workflows/build.yml
      - build.sh

env:
  VERSION: 4.0.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: sip_simple_sdk
          path:
            dist/*.deb
